### ISSUE TITLE
How to show Custom HTML 5 Videos and Any Other Third Party Videos except Vimeo and Youtube..?

### ISSUE THREAD

**Issue by GRASPARK** [staaky/fresco#15]
Hello,

Currently it is handling Only Media Types of "Youtube", "Image" and "Video".

But how to handle to show Custom HTML 5 Videos and Any Other Third Party Videos except Vimeo and Youtube..?

**Comment by staaky** [comment]
Fresco can’t handle custom video files. I chose to limit it to Youtube and Vimeo because they offer iframe based players that are easily embedded without any extra work on your end. They take care of everything, encoding in multiple formats, hosting, they give you a player that works everywhere and they maintain it. I wouldn’t recommend trying to set that up yourself.
